# SPDX-FileCopyrightText: 2026 Luke Galea
#
# SPDX-License-Identifier: MIT

defmodule AshAcp.SurfaceProvider do
  @moduledoc """
  Optional host-implemented seam carrying A2UI surface descriptors.

  A2UI payloads are generated by the host (e.g. `ash_a2ui`). This library
  **never generates, validates or re-defines them** — it carries whatever JSON
  the host returns, verbatim, under the `session/update`'s `update.surface`
  field, exactly as `ash_graphql` carries host-provided context.

  Returning `nil` (or configuring no provider) simply omits the field.
  """

  @callback surface(session :: term(), meta :: map()) :: surface :: map() | nil
end
